### ISSUE TITLE
Possible bug in `element_markdown()`

### ISSUE THREAD

**Issue by fmmattioni** [wilkelab/ggtext#40]
I have been trying to place the following label on my axis: **[La<sup>-</sup>] (mmol·L<sup>-1</sup>)**.

The problem is that it seems the use of `[ ]` and `( )` is causing a bug.

**reprex with bug:**

``` r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(mpg, hp)) +
  geom_point() +
  labs(x = "[La<sup>-</sup>] (mmol·L<sup>-1</sup>)") +
  theme(axis.title.x = element_markdown())
#> Error: gridtext has encountered a tag that isn't supported yet: <a>
#> Only a very limited number of tags are currently supported.
```
<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**When I use `( )` instead of `[ ]`, the bug seems to disappear:**

``` r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(mpg, hp)) +
  geom_point() +
  labs(x = "(La<sup>-</sup>) (mmol·L<sup>-1</sup>)") +
  theme(axis.title.x = element_markdown())
```

![](https://i.imgur.com/vpdZUfO.png)

<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Any thoughts on this?

**Comment by clauswilke** [comment]
This happens because the pattern `[...] (...)` is interpreted as a link in markdown. One workaround is to use the html entities representing [ and ]:

``` r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(mpg, hp)) +
  geom_point() +
  labs(x = "&#91;La<sup>-</sup>&#93; (mmol·L<sup>-1</sup>)") +
  theme(axis.title.x = element_markdown())
```

![](https://i.imgur.com/8ZB0BOF.png)

<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The other is to use a non-breaking space. While `element_markdown()` doesn't actually handle non-breaking spaces correctly, it's sufficient here to stop the markdown interpreter from inserting a link:

``` r
library(ggplot2)
library(ggtext)

ggplot(mtcars, aes(mpg, hp)) +
  geom_point() +
  labs(x = "[La<sup>-</sup>]&nbsp;(mmol·L<sup>-1</sup>)") +
  theme(axis.title.x = element_markdown())
```

![](https://i.imgur.com/joVXWW3.png)

<sup>Created on 2020-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by fmmattioni** [comment]
Oohh, that is true.. I am so sorry, I have completed overlooked this.. thank you, @clauswilke!
